#cloud-config
coreos:
  etcd:
    discovery: https://discovery.etcd.io/1eae1e0072a48c21a06d5ff1fc2d2d7c
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
