#cloud-config
coreos:
  etcd:
    discovery: https://discovery.etcd.io/0193a3d459a52f54259a482c27293ee0
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
write_files:
  - path: /etc/logstash.conf
    permissions: 0644
    owner: root
    content: |
      input {
        stdin {
          type => "stdin-type"
        }

        syslog {
          # use all defaults
        }

        # file {
        #   type => "syslog"
              #   path => [ "/var/log/*.log", "/var/log/messages", "/var/log/syslog" ]
        #   start_position => "beginning"
        # }
      }

      output {
        stdout {
          codec => rubydebug
        }
      
        elasticsearch {
          embedded => true
        }
      }
