#cloud-config
coreos:
  etcd:
    discovery: https://discovery.etcd.io/0193a3d459a52f54259a482c27293ee0
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
